import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiVuedotjs,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiDocker,
  SiAwslambda,
  SiVercel,
} from "react-icons/si"

export const iconMap: Record<string, React.ComponentType<any>> = {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiVuedotjs,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiDocker,
  SiAwslambda,
  SiVercel,
}
